### PR TITLE
Fix for latest qt5 avaliable from homebrew on OS X

### PR DESCRIPTION
**Pull request by TheSkorm**
This fixes this compile issue on OS X:
```
/Users/mwheeler/Downloads/cantata/gui/application.cpp:46:17: error: no viable conversion from 'ProxyStyle' to 'ProxyStyle *'
    ProxyStyle *proxy=ProxyStyle(ProxyStyle::VF_Side|ProxyStyle::VF_Top);
                ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/cantata.dir/gui/application.cpp.o] Error 1
make[1]: *** [CMakeFiles/cantata.dir/all] Error 2
make: *** [all] Error 2
```

I've also updated the README to reflect installing qt5 from homebrew.

### CODE REVIEW

**Comment by a17r** [comment]
Please change the commit message to something more descriptive, this probably is a valid fix for anyone trying to build with Qt-5.9.1, not just homebrew...

**Comment by CDrummond** [comment]
Thanks. The build failure was a stupid typo. I don't build for mac often - hence why I had not found and fixed.
