### ISSUE TITLE
Build Failure With SpeexDSP>=1.2rc2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CDrummond/cantata#627]
```
Which version of Cantata?
r5668

Which build? KDE, Qt4, Qt5, Windows, Ubuntu, Mac?
KDE and Qt5

When the speex devs split the speex codec library and the speex DSP library 
into separate source trees starting with v1.2rc2 they made the following 
changes to /usr/include/speex/speex_config_types.h:

#ifndef __SPEEX_TYPES_H__                    #ifndef __SPEEX_TYPES_H__
#define __SPEEX_TYPES_H__                    #define __SPEEX_TYPES_H__

/* these are filled in by configure */       | #include <stdint.h>
typedef short spx_int16_t;                   |
typedef unsigned short spx_uint16_t;         | typedef int16_t spx_int16_t;
typedef int spx_int32_t;                     | typedef uint16_t spx_uint16_t;
typedef unsigned int spx_uint32_t;           | typedef int32_t spx_int32_t;
                                             > typedef uint32_t spx_uint32_t;

#endif                                       #endif

This now results in a build failure when trying to build with speexdsp-1.2rc2 
or higher:

In file included from /usr/include/speex/speexdsp_types.h:122:0,
                 from /usr/include/speex/speex_resampler.h:87,
                 from /home/user/Projects/cantata-kde-svn/src/cantata-kde-svn/3rdparty/ebur128/ebur128.c:34:
/usr/include/speex/speexdsp_config_types.h:13:9: error: unknown type name 
‘uint16_t’
 typedef uint16_t spx_uint16_t;
         ^
/usr/include/speex/speexdsp_config_types.h:15:9: error: unknown type name 
‘uint32_t’
 typedef uint32_t spx_uint32_t;
         ^
Scanning dependencies of target qtiocompressor
/home/user/cantata-kde-svn/src/cantata-kde-svn/3rdparty/ebur128/ebur128.c: In 
function ‘ebur128_check_true_peak’:
/home/user/cantata-kde-svn/src/cantata-kde-svn/3rdparty/ebur128/ebur128.c:395:19
: warning: comparison between signed and unsigned integer expressions 
[-Wsign-compare]
     for (i = 0; i < out_len; ++i) {
                   ^
3rdparty/ebur128/CMakeFiles/ebur128.dir/build.make:54: recipe for target 
'3rdparty/ebur128/CMakeFiles/ebur128.dir/ebur128.o' failed
make[2]: *** [3rdparty/ebur128/CMakeFiles/ebur128.dir/ebur128.o] Error 1
CMakeFiles/Makefile2:305: recipe for target 
'3rdparty/ebur128/CMakeFiles/ebur128.dir/all' failed
make[1]: *** [3rdparty/ebur128/CMakeFiles/ebur128.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Original issue reported on code.google.com by `hbdee.a...@gmail.com` on 15 Feb 2015 at 3:17
