### ISSUE TITLE
Fails to build with upcoming ffmpeg 3.5

### ISSUE THREAD

**Issue by llimeht** [CDrummond/cantata#1172]
Hi!

The Debian ffmpeg maintainers have done a test rebuild of packages with a new snapshot of ffmpeg 3.5. There are various API changes that will hit with 3.5 and, while this is a pre-release version, it is anticipated that the API for 3.5 is stable at this point.

Cantata does not successfully build against ffmpeg 3.5 due to some API changes. The Debian ffmpeg maintainers summarise the changes as follows:

> Incomplete list of changes (based on looking at common build failures):
>- Some fields in AVCodecContext have been removed and replaced with private
>  options which can be set using the av_opt_set* APIs
>- Most CODEC_* constants have been renamed to AV_CODEC_*
>- The buffer constants FF_INPUT_BUFFER_PADDING_SIZE and FF_MIN_BUFFER_SIZE
 > have been renamed to AV_INPUT_BUFFER_PADDING_SIZE and
>  AV_INPUT_BUFFER_MIN_SIZE.
>- The old resampling API provided by libavcodec has been removed. Use
>  libswresample instead.
>- The libavfilter/avfiltergraph.h header has been removed, include
>  libavfilter/avfilter.h instead.
>- The AVFrac structure (representing mixed rational numbers) has been
>  removed.

(the 3rd point looks to be the relevant one here)

The relevant section from the build log is as below; g++ will of course have bailed out at the first error so there may be more beyond this.

```
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:43:85: error: 'FF_INPUT_BUFFER_PADDING_SIZE' was not declared in this scope
 #define BUFFER_SIZE ((((AVCODEC_MAX_AUDIO_FRAME_SIZE * 3) / 2) * sizeof(int16_t)) + FF_INPUT_BUFFER_PADDING_SIZE)
                                                                                     ^
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:106:18: note: in expansion of macro 'BUFFER_SIZE'
     float buffer[BUFFER_SIZE / 2 + 1];
                  ^~~~~~~~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:43:85: note: suggested alternative: 'AV_INPUT_BUFFER_PADDING_SIZE'
 #define BUFFER_SIZE ((((AVCODEC_MAX_AUDIO_FRAME_SIZE * 3) / 2) * sizeof(int16_t)) + FF_INPUT_BUFFER_PADDING_SIZE)
                                                                                     ^
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:106:18: note: in expansion of macro 'BUFFER_SIZE'
     float buffer[BUFFER_SIZE / 2 + 1];
                  ^~~~~~~~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp: In constructor 'FfmpegInput::Handle::Handle()':
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:43:85: error: 'FF_INPUT_BUFFER_PADDING_SIZE' was not declared in this scope
 #define BUFFER_SIZE ((((AVCODEC_MAX_AUDIO_FRAME_SIZE * 3) / 2) * sizeof(int16_t)) + FF_INPUT_BUFFER_PADDING_SIZE)
                                                                                     ^
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:65:43: note: in expansion of macro 'BUFFER_SIZE'
         audioBuffer = (int16_t*)av_malloc(BUFFER_SIZE);
                                           ^~~~~~~~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:43:85: note: suggested alternative: 'AV_INPUT_BUFFER_PADDING_SIZE'
 #define BUFFER_SIZE ((((AVCODEC_MAX_AUDIO_FRAME_SIZE * 3) / 2) * sizeof(int16_t)) + FF_INPUT_BUFFER_PADDING_SIZE)
                                                                                     ^
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:65:43: note: in expansion of macro 'BUFFER_SIZE'
         audioBuffer = (int16_t*)av_malloc(BUFFER_SIZE);
                                           ^~~~~~~~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp: In constructor 'FfmpegInput::FfmpegInput(const QString&)':
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:154:52: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
             if (handle->formatContext->streams[j]->codec->codec_type ==
                                                    ^~~~~
In file included from /<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:22:0:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:154:52: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
             if (handle->formatContext->streams[j]->codec->codec_type ==
                                                    ^~~~~
In file included from /<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:22:0:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:154:52: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
             if (handle->formatContext->streams[j]->codec->codec_type ==
                                                    ^~~~~
In file included from /<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:22:0:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:173:85: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
         handle->codecContext = handle->formatContext->streams[handle->audioStream]->codec;
                                                                                     ^~~~~
In file included from /<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:22:0:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:173:85: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
         handle->codecContext = handle->formatContext->streams[handle->audioStream]->codec;
                                                                                     ^~~~~
In file included from /<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:22:0:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:173:85: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
         handle->codecContext = handle->formatContext->streams[handle->audioStream]->codec;
                                                                                     ^~~~~
In file included from /<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:22:0:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:876:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp: In member function 'virtual float* FfmpegInput::buffer() const':
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:257:29: error: 'struct FfmpegInput::Handle' has no member named 'buffer'; did you mean 'bufferList'?
     return handle ? handle->buffer : 0;
                             ^~~~~~
                             bufferList
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp: In member function 'virtual size_t FfmpegInput::readFrames()':
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:43:85: error: 'FF_INPUT_BUFFER_PADDING_SIZE' was not declared in this scope
 #define BUFFER_SIZE ((((AVCODEC_MAX_AUDIO_FRAME_SIZE * 3) / 2) * sizeof(int16_t)) + FF_INPUT_BUFFER_PADDING_SIZE)
                                                                                     ^
/<<PKGBUILDDIR>>/replaygain/ffmpeginput.cpp:325:35: note: in expansion of macro 'BUFFER_SIZE'
     while (handle->currentBytes < BUFFER_SIZE) {
                                   ^~~~~~~~~~~
```

Forwarded from Debian Bug#[888363](https://bugs.debian.org/888363)

**Comment by CDrummond** [comment]
Thanks for the advanced warning. ffmpeg seems to continually change API :-( Think I might replace API calls with calling the binary instead.

**Comment by CDrummond** [comment]
I've made some changes, so that I now (under Ubuntu 17.10) no longer get any deprecated API warnings. However, I don't have 3.5 installed. Can you checkout git/master and compile against 3.5?

**Comment by Thaodan** [comment]
I did build latest ffmpeg via git and build cantata against it and building is fine.

**Comment by CDrummond** [comment]
Thanks! I assume this latest git is the same as 3.5? If so, then I guess this can be closed?

**Comment by Thaodan** [comment]
Yes it was "ffmpeg-git-3.5.r89901.ga026a3efae-1" to be exact, I just installed 
ffmpeg-git from the aur for the time of building.
